apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  namespace: enrollment-namespace
spec:
  type: NodePort
  selector:
    app: enrollment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8095
